---
- name: Apache | Install packages
  yum:
    name: httpd
    state: present
  notify:
    - start-httpd
    
- name: Apache | Configure /etc/httpd/httpd.conf
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/httpd.conf
    owner: root
    group: root
  notify:
    - restart-httpd
